CREATE DATABASE IF NOT EXISTS financial_app;

USE financial_app;

-- Users Table
CREATE TABLE IF NOT EXISTS Users (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Name VARCHAR(100),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Categories Table
CREATE TABLE IF NOT EXISTS Categories (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT,
    Name VARCHAR(100) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES Users(ID) ON DELETE CASCADE,
    CONSTRAINT unique_category_per_user UNIQUE (UserId, Name)
);

-- Accounts Table
CREATE TABLE IF NOT EXISTS Accounts (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT NOT NULL,
    Account_Name VARCHAR(255) NOT NULL,
    Initial_Amount DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES Users(ID) ON DELETE CASCADE,
    CONSTRAINT unique_account_name_per_user UNIQUE (UserId, Account_Name)
);

-- Transactions Table
CREATE TABLE IF NOT EXISTS Transactions (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    AccountID INT NOT NULL,
    CategoryID INT,
    Value DECIMAL(10, 2) NOT NULL,
    Type ENUM('income', 'expense') NOT NULL,
    Date DATE NOT NULL,
    Description TEXT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (AccountID) REFERENCES Accounts(ID) ON DELETE CASCADE,
    FOREIGN KEY (CategoryID) REFERENCES Categories(ID) ON DELETE SET NULL
); 